text = input('digite algo: ')
print('Oque você digitou tem o tipo primitivo: ', type(text))
print('Oque você digitou é Númerico?: ', text.isnumeric())
print('Oque vocè digitou é Alfabetico?: ', text.isalpha())
print('Oque você digitou é Alfanumerico?: ', text.isalnum())
print('Oque você digitou está tudo em Maiusculo?: ', text.isupper())
print('Oque você digitou está tudo em Minusculo?: ', text.islower())
print('Oque você digitou é Capitalizado?: ', text.istitle())
print('Oque você digitou só possui espaços?: ', text.isspace())
